name: test-serve-deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Clone complete"
      - name: install
        run: |
          npm install
      - name: build
        run: |
          npm run build
      - name: serve
        run: |
          npm run serve
      - run: echo "Status ${{ job.status }}"
